### ISSUE TITLE
I don't know how to start with that bundle

### ISSUE THREAD

**Issue by Axxon** [neomerx/limoncello#10]
Hello, i start to use JSON-API with your component and i try today to add this bundle layer on. I shortly read the code but honestly i don't know how to approach him. Somebody could explain shortly how best integrate with a symfony project in awaiting of a short wiki.

(Minimum question = absence of service is deliberate ?)

**Comment by neomerx** [comment]
Hi, you need either https://github.com/neomerx/limoncello-collins or https://github.com/neomerx/limoncello-shot

**Comment by neomerx** [comment]
if you want to bundle it with symfony it's likely to be non-trivial task. For example it took some code to make demo with Laravel https://github.com/neomerx/limoncello-collins/commit/e029c43c03154b97d4a72bb8e7bc8c7e8668ccd3

However it includes lots of pure demo/samples code

**Comment by neomerx** [comment]
Symfony integration is in https://github.com/neomerx/limoncello/issues/12

**Comment by Axxon** [comment]
Hello, a found a way to make it work (temp solution) i stay tune with @drewclauson for a symfony integration bundle.
