### ISSUE TITLE
Non standard ID's (Mongo)

### ISSUE THREAD

**Issue by Daveawb** [neomerx/limoncello#11]
Hi,

I've not got a lot of time to go through the source at the moment, I'm using Mongo along with a custom build of Limoncello on Laravel 5 but having problems integrating Mongo models where the id is '_id'.

Is there any way to customise which field should be used for ID within the Schema currently?

Thanks

**Comment by jcloutz** [comment]
You should be able to do the following, if I'm understanding you correctly.

```
    public function getId($author)
    {
        /** @var Author $author */
        return $author->id;
    }
```
example from here: https://github.com/neomerx/limoncello-shot/blob/master/app/Schemas/AuthorSchema.php

**Comment by neomerx** [comment]
@Daveawb it should solve your problem. If not don't hesitate to ask.
@jcloutz thank you for your help

**Comment by Daveawb** [comment]
@jcloutz Perfect, thank you.
@neomerx  It does solve the problem, thanks.
