### ISSUE TITLE
Lumen 5.2 support on limoncello-shot?

### ISSUE THREAD

**Issue by adamkelso** [neomerx/limoncello#14]
Sorry for not putting this on the right project, but the issues were turned off on the "shot" project. Is there any chance the project will be updated for lumen 5.2? Currently it requires 5.1

**Comment by neomerx** [comment]
Sorry but it took a lot of time and efforts to make the project way more advanced. Dev version is [published](https://github.com/neomerx/limoncello-shot/tree/lumen) for Lumen 5.2
