### ISSUE TITLE
Seeing some weirdness in composer

### ISSUE THREAD

**Issue by mmucklo** [neomerx/limoncello#15]
With the latest release of json-api (v0.7.0), installing limoncello is giving a strange error

```
- neomerx/limoncello v0.5.1 requires neomerx/json-api ~0.6.0 -> no matching package found.
```

**Comment by neomerx** [comment]
Hmm... It references only 0.6.x Are you using limoncello 0.5.1? Not dev branch or something like that?

``` json
  "require": {
    "php": ">=5.5.0",
    "symfony/http-kernel": "~2.6.7|~2.7.0|~2.8.0|~3.0.0",
    "neomerx/json-api": "~0.6.0"
  },
```

**Comment by neomerx** [comment]
Aha, you are trying to use current limoncello with json-api 0.7.0, right?

**Comment by neomerx** [comment]
@mmucklo I haven't received any feedback from you so I can only guess. I think you tried to switch limoncello to 0.7.0 in `composer.json`. Those versions have are incompatible. I'm working on new version of limoncello and limoncello-shot (latest lumen) which use json-api 0.7.0

I'm closing the issue. If you feel it's still exist please let me know.
