### ISSUE TITLE
Symphony might convert HTTP Request body to array

### ISSUE THREAD

**Issue by neomerx** [neomerx/limoncello#6]
which leads to exception 'ErrorException' with message 'Array to string conversion' in /limoncello/src/Http/FrameworkIntegration.php:31

**Comment by sumeko** [comment]
is this the reason why i can't make the "included" works?

**Comment by neomerx** [comment]
I think it's not. I just found that on under some circumstances symfony unexpectedly (to me :smile: ) converts body string to array. So this issue is basically a reminder to fix it in the next release.
Actually symfony must return string for `Request::getContent` with `$asResource = false` input parameter but it did for under some conditions. I think it might be for empty body. Sadly I was in the middle of something when got the error and didn't make good notices what led to it.

**Comment by neomerx** [comment]
I might accidentally passed an array as `$content` parameter to `Request` constructor and got the error. So there is no error at all probably. Just need to check a bit more.

**Comment by neomerx** [comment]
I've found the reason. I passed the array myself during PhpUnit tests as a parameter to Symfony Request. Thus this issue cannot happen during production usage and can only be reproduced in tests.

**Comment by nvshivakumar** [comment]
Hi is there any clue to connect symfony with neomerx . Shall i directly implement it in api controller?

**Comment by neomerx** [comment]
@nvshivakumar As far as I know @drewclauson did json-api integration bundle for Symfony
